package com.micharksi.mbasic;

public enum TokenType {
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE,
    COMMA, DOT, MINUS, PLUS, SEMICOLON, SLASH, STAR,
    PERCENT, BITWISE_AND, BITWISE_OR,

    BANG, BANG_EQUAL,
    EQUAL, EQUAL_EQUAL,
    GREATER, GREATER_EQUAL,
    LESS, LESS_EQUAL,
    LOGICAL_AND, LOGICAL_OR,

    INT, CHAR, FLOAT, STRING, BIN, HEX, IDENTIFIER, BOOL,

    DO, LET, IF, ELSE, RETURN, NAMESPACE,

    TRUE, FALSE, NULL,

    EOF
}
